### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by jonathan-daniel** [rafalp/Misago#1138]
Hello,

The `dev` script, and also` gulp build` doesnt seem to work on Windows.

Is windows supported?

The dev script just hangs and gulp build gives an error:
```

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\ntq\Documents\recenthacks\Misago\frontend\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\ntq\Documents\recenthacks\Misago\frontend\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\ntq\Documents\recenthacks\Misago\frontend\gulpfile.js:27:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by rafalp** [comment]
`dev` script is implemented using bash, so there's no way to run it (to my knowledge) but its only shortcuts. Readme contains instruction how to start local instance on windows without using it.

Gulp error looks like something is outdated. We may have to include packages-lock.json to prevent npm from installing too new and uncompatibile things for our frontend.
