### ISSUE TITLE
Investigate if dev docker setup is broken

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1208]
Continuing from #1205 apparently, it's possible for dev docker to build containers without files required to run the dev instance:

```
$ docker-compose up 
Starting misago_postgres_1 ... done
Starting misago_redis_1    ... done
Starting misago_celery_1   ... done
Starting misago_misago_1   ... done
Attaching to misago_redis_1, misago_postgres_1, misago_celery_1, misago_misago_1
postgres_1  | 2019-03-04 09:56:45.325 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
redis_1     | 1:C 04 Mar 2019 09:56:45.204 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 04 Mar 2019 09:56:45.205 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
postgres_1  | 2019-03-04 09:56:45.325 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1     | 1:C 04 Mar 2019 09:56:45.205 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1  | 2019-03-04 09:56:45.327 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
redis_1     | 1:M 04 Mar 2019 09:56:45.209 * Running mode=standalone, port=6379.
postgres_1  | 2019-03-04 09:56:45.357 UTC [21] LOG:  database system was shut down at 2019-03-04 09:56:36 UTC
redis_1     | 1:M 04 Mar 2019 09:56:45.209 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 04 Mar 2019 09:56:45.209 # Server initialized
redis_1     | 1:M 04 Mar 2019 09:56:45.210 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 04 Mar 2019 09:56:45.210 * DB loaded from disk: 0.000 seconds
misago_1    | python: can't open file 'manage.py': [Errno 2] No such file or directory
misago_misago_1 exited with code 2
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/bin/celery", line 10, in <module>
celery_1    |     sys.exit(main())
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celery_1    |     _main()
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celery_1    |     cmd.execute_from_commandline(argv)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
celery_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
celery_1    |     argv = self.setup_app_from_commandline(argv)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
celery_1    |     self.app = self.find_app(app)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
celery_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
celery_1    |     sym = symbol_by_name(app, imp=imp)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
celery_1    |     return imports.symbol_by_name(name, imp=imp)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celery_1    |     module = imp(module_name, package=package, **kwargs)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
celery_1    |     return imp(module, package=package)
celery_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery_1    |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
celery_1    | ModuleNotFoundError: No module named 'devproject'
misago_celery_1 exited with code 1
```

The focus points of above are following:

- `misago_1    | python: can't open file 'manage.py': [Errno 2] No such file or directory` means that `manage.py` was not included in main `misago` service container.
- `celery_1    | ModuleNotFoundError: No module named 'devproject'` means that `devproject` was not present in `celery` service's container.

**Comment by rafalp** [comment]
I've cloned current master and containers have built successfully and application is running without errors.
