### ISSUE TITLE
Trouble of social login

### ISSUE THREAD

**Issue by mzch** [rafalp/Misago#1321]
Hi,

I installed Misago and has set all social logins.
When I login using Google or Twitter, Misago says, "Something's broken..."

And when using Facebook, Misago shows Sign in with Facebook page, but trying to finish to sign up, it says, "Unknown Error has occored."

Anyone can tell me how to fix this issue?

**Comment by rafalp** [comment]
Hello, can you share the logs please?

**Comment by mzch** [comment]
Here you are.
```
[2019-10-19 12:42:36,998] ERROR Internal Server Error: /login/google/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 12, in do_auth
    for field_name in backend.setting('FIELDS_STORED_IN_SESSION', []):
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 31, in setting
    return self.strategy.setting(name, default=default, backend=self)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 8, in setting
    backend_settings = self.request.socialauth[backend.name]["settings"]
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
KeyError: 'google-oauth2'
[2019-10-19 12:43:35,287] ERROR Internal Server Error: /login/google/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 12, in do_auth
    for field_name in backend.setting('FIELDS_STORED_IN_SESSION', []):
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 31, in setting
    return self.strategy.setting(name, default=default, backend=self)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 8, in setting
    backend_settings = self.request.socialauth[backend.name]["settings"]
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
KeyError: 'google-oauth2'
[2019-10-19 12:44:07,069] ERROR Internal Server Error: /login/twitter/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 27, in do_auth
    return backend.start()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 35, in start
    return self.strategy.redirect(self.auth_url())
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 167, in auth_url
    token = self.set_unauthorized_token()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 223, in set_unauthorized_token
    token = self.unauthorized_token()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 247, in unauthorized_token
    method=self.REQUEST_TOKEN_METHOD
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 234, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token
[2019-10-19 12:46:09,803] ERROR Internal Server Error: /login/google/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 12, in do_auth
    for field_name in backend.setting('FIELDS_STORED_IN_SESSION', []):
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 31, in setting
    return self.strategy.setting(name, default=default, backend=self)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 8, in setting
    backend_settings = self.request.socialauth[backend.name]["settings"]
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
KeyError: 'google-oauth2'
[2019-10-19 12:46:33,966] ERROR Internal Server Error: /login/google/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 12, in do_auth
    for field_name in backend.setting('FIELDS_STORED_IN_SESSION', []):
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 31, in setting
    return self.strategy.setting(name, default=default, backend=self)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 8, in setting
    backend_settings = self.request.socialauth[backend.name]["settings"]
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
KeyError: 'google-oauth2'
[2019-10-19 12:47:20,576] ERROR Internal Server Error: /complete/github/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 56, in complete
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 39, in do_complete
    user = backend.continue_pipeline(partial)
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 201, in continue_pipeline
    **partial.kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 20, in authenticate
    return backend.authenticate(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/usr/local/lib/python3.7/site-packages/social_core/pipeline/partial.py", line 34, in wrapper
    *args, **kwargs) or {}
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/pipeline.py", line 227, in create_user_with_form
    send_welcome_email(request, new_user)
  File "/usr/local/lib/python3.7/site-packages/misago/users/registration.py", line 20, in send_welcome_email
    context={"settings": settings},
  File "/usr/local/lib/python3.7/site-packages/misago/core/mail.py", line 40, in mail_user
    message.send()
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/message.py", line 248, in get_connection
    self.connection = get_connection(fail_silently=fail_silently)
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/__init__.py", line 35, in get_connection
    return klass(fail_silently=fail_silently, **kwds)
  File "/usr/local/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 33, in __init__
    "EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set "
ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.
[2019-10-19 12:54:36,707] ERROR Internal Server Error: /login/twitter/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 27, in do_auth
    return backend.start()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 35, in start
    return self.strategy.redirect(self.auth_url())
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 167, in auth_url
    token = self.set_unauthorized_token()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 223, in set_unauthorized_token
    token = self.unauthorized_token()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 247, in unauthorized_token
    method=self.REQUEST_TOKEN_METHOD
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 234, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token
[2019-10-19 12:54:43,221] ERROR Internal Server Error: /login/google/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 12, in do_auth
    for field_name in backend.setting('FIELDS_STORED_IN_SESSION', []):
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 31, in setting
    return self.strategy.setting(name, default=default, backend=self)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 8, in setting
    backend_settings = self.request.socialauth[backend.name]["settings"]
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
KeyError: 'google-oauth2'
[2019-10-19 13:01:02,630] ERROR Internal Server Error: /login/google/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 12, in do_auth
    for field_name in backend.setting('FIELDS_STORED_IN_SESSION', []):
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 31, in setting
    return self.strategy.setting(name, default=default, backend=self)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/strategy.py", line 8, in setting
    backend_settings = self.request.socialauth[backend.name]["settings"]
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
KeyError: 'google-oauth2'
```

**Comment by rafalp** [comment]
This looks like a bug all-right. `provider` attribute should be same as strategy's `name`, and for google that's `google-oauth2`.

Can you please also show logs for twitter and facebook login?

**Comment by mzch** [comment]
Hi,

Sorry, now I tried Facebook, I could sign in successfully.

And tried Twitter, the following error was logged:
```
[2019-10-19 23:34:07,390] ERROR Internal Server Error: /login/twitter/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 34, in social_auth_view_wrapper
    return f(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/misago/socialauth/views.py", line 42, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "/usr/local/lib/python3.7/site-packages/social_core/actions.py", line 27, in do_auth
    return backend.start()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 35, in start
    return self.strategy.redirect(self.auth_url())
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 167, in auth_url
    token = self.set_unauthorized_token()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 223, in set_unauthorized_token
    token = self.unauthorized_token()
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/oauth.py", line 247, in unauthorized_token
    method=self.REQUEST_TOKEN_METHOD
  File "/usr/local/lib/python3.7/site-packages/social_core/backends/base.py", line 234, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token
```

**Comment by mzch** [comment]
Twitter resource URL is https://api.twitter.com/oauth2/token ...?

**Comment by rafalp** [comment]
I don't know ;) I've been wondering if perhaps Twitter has changed their OAuth API, but Python social auth's Twitter backend was last changed [3 years ago](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/twitter.py). Are you sure you've configured twitter backend correctly?

**Comment by mzch** [comment]
Well, Twitter often changes their API.
Please see https://developer.twitter.com/en/docs/basics/authentication/api-reference/token
Yes, callback address is https://example.com or https://example.com/complete/twitter for https://example.com, isn't it?

**Comment by mzch** [comment]
sorry, /oauth/request_token API exists...
https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token

**Comment by rafalp** [comment]
I'll fix Google Auth provider being borked today in Misago 0.25
