### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by bgreatfit** [rafalp/Misago#1352]
Internal Server Error: /admincp/
misago_1    | Traceback (most recent call last):
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
misago_1    |     response = get_response(request)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 106, in _get_response
misago_1    |     response = middleware_method(request, callback, callback_args, callback_kwargs)
misago_1    |   File "/srv/misago/misago/admin/middleware.py", line 17, in process_view
misago_1    |     return self.check_admin_authorization(request)
misago_1    |   File "/srv/misago/misago/admin/middleware.py", line 23, in check_admin_authorization
misago_1    |     return login(request)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
misago_1    |     return view(request, *args, **kwargs)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
misago_1    |     response = view_func(request, *args, **kwargs)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
misago_1    |     response = view_func(request, *args, **kwargs)
misago_1    |   File "/srv/misago/misago/admin/views/auth.py", line 31, in login
misago_1    |     return render(request, "misago/admin/login.html", {"form": form, "target": target})
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
misago_1    |     content = loader.render_to_string(template_name, context, request, using=using)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
misago_1    |     return template.render(context, request)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
misago_1    |     return self.template.render(context)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 169, in render
misago_1    |     with context.bind_template(self):
misago_1    |   File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
misago_1    |     return next(self.gen)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/debug_toolbar/panels/templates/panel.py", line 50, in _request_context_bind_template
misago_1    |     context = processor(self.request)
misago_1    |   File "/srv/misago/misago/users/context_processors.py", line 45, in preload_user_json
misago_1    |     serialized_user = serializer(request.user, context={"acl": request.user_acl}).data
misago_1    |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 563, in data
misago_1    |     ret = super(Serializer, self).data
misago_1    |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
misago_1    |     self._data = self.to_representation(self.instance)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 530, in to_representation
misago_1    |     ret[field.field_name] = field.to_representation(attribute)
misago_1    |   File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 1889, in to_representation
misago_1    |     return method(value)
misago_1    |   File "/srv/misago/misago/users/serializers/user.py", line 92, in get_real_name
misago_1    |     return obj.get_real_name()
misago_1    |   File "/srv/misago/misago/users/models/user.py", line 331, in get_real_name
misago_1    |     return self.profile_fields.get("real_name")
misago_1    | AttributeError: 'str' object has no attribute 'get'

**Comment by bgreatfit** [comment]
@rafalp  pls help with this error

**Comment by soloviola** [comment]
@bgreatfit 

What I found is in 
![image](https://user-images.githubusercontent.com/4130016/106799480-4dd07280-662d-11eb-9757-99e63bd30285.png)

Change `profile_fields.get("real_name")` to `profile_fields`

**Comment by rafalp** [comment]
This seems very wrong. `profile_fields` is supposed to be hstore with custom profile fields and represented as dict in python.

How are you experiencing this bug?

**Comment by bgreatfit** [comment]
> This seems very wrong. `profile_fields` is supposed to be hstore with custom profile fields and represented as dict in python.
> 
> How are you experiencing this bug?

Just launched the app on my local server after following the Readme instructions

**Comment by jeroenbakker-atmind** [comment]
I reproduced the same/a similar issue.
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/t/only-one-spacecraft-has-visited-distant-uranus/2/

Django Version: 3.2.15
Python Version: 3.11.1
Installed Applications:
['misago',
 'misago.users',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.postgres',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'ariadne_django',
 'celery',
 'debug_toolbar',
 'mptt',
 'rest_framework',
 'social_django',
 'misago.admin',
 'misago.acl',
 'misago.analytics',
 'misago.cache',
 'misago.core',
 'misago.conf',
 'misago.icons',
 'misago.themes',
 'misago.markup',
 'misago.legal',
 'misago.categories',
 'misago.threads',
 'misago.readtracker',
 'misago.search',
 'misago.oauth2',
 'misago.socialauth',
 'misago.graphql',
 'misago.faker',
 'misago.menus',
 'misago.plugins']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'misago.users.middleware.RealIPMiddleware',
 'misago.core.middleware.FrontendContextMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'misago.cache.middleware.cache_versions_middleware',
 'misago.conf.middleware.dynamic_settings_middleware',
 'misago.socialauth.middleware.socialauth_providers_middleware',
 'misago.users.middleware.UserMiddleware',
 'misago.acl.middleware.user_acl_middleware',
 'misago.core.middleware.ExceptionHandlerMiddleware',
 'misago.users.middleware.OnlineTrackerMiddleware',
 'misago.admin.middleware.AdminAuthMiddleware',
 'misago.threads.middleware.UnreadThreadsCountMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/misago/misago/threads/views/thread.py", line 18, in get
    frontend_context = self.get_frontend_context(request, thread, posts)
  File "/srv/misago/misago/threads/views/thread.py", line 47, in get_frontend_context
    "POSTS": posts.get_frontend_context(),
  File "/srv/misago/misago/threads/viewmodels/posts.py", line 107, in get_frontend_context
    ).data
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/srv/misago/misago/users/serializers/user.py", line 92, in get_real_name
    return obj.get_real_name()
  File "/srv/misago/misago/users/models/user.py", line 329, in get_real_name
    return self.profile_fields.get("real_name")

Exception Type: AttributeError at /t/only-one-spacecraft-has-visited-distant-uranus/2/
Exception Value: 'str' object has no attribute 'get'
```

Steps to reproduce are:

* Download misago 0.28.2 branch from github
* Init development docker (`./dev init`)
* `docker-compose up`
* In different terminal start the import of fake data (`./dev fakedata`)
* After import In Browser (used private browsing) navigate to `127.0.0.1:8000`

Will check if this also happens with by restoring/migrating a production database and by running these steps on a clean machine.

**Comment by rafalp** [comment]
I guess the issue is `profile_fields` on user model being set to string when it should be a dict?

**Comment by rafalp** [comment]
@jeroenbakker-atmind You mention doing a change through admin panel. Can you mention what change was that?

**Comment by rafalp** [comment]
Good news: this doesn't seem to be a bug with Misago!

Bad news: this error occurring means that database driver didn't retrieve valid hstore extension ID from `pg_type` table when initializing connection. Because it has wrong ID, it doesn't understand  that `profile_fields` value is from hstore field. So it returns it as string, which results in an error.

**Comment by rafalp** [comment]
@jeroenbakker-atmind I've found a new lead for what can cause this issue. Can you please tell me what memory limits are set in your docker configuration?

**Comment by rafalp** [comment]
I've couldn't reproduce this, but there are two possibilities now I would like to check:

- Django caches wrong object ID (`OID`) for HStore extension for current connection, which results in HStore extension registering incorrectly for current DB connection
- Django's `connection_created` has been garbage collected which means its no longer registering HStore extension for new database connections.

**Comment by rafalp** [comment]
I'm unable to reproduce this, but I've added logic that will catch when this bug happens and will print error message with debug data that will help me investigate this further or let me bring this issue to Django dev team, also have a [bug for this](https://code.djangoproject.com/ticket/29001), but requested more information about it.

This error will **ONLY DISPLAY IN DEBUG** so production deployments and deployments with misago-docker are safe and will not display the error to the users:


<img width="824" alt="Zrzut ekranu 2023-01-26 o 21 59 49" src="https://user-images.githubusercontent.com/750553/214950261-b0f73cc6-befa-4e09-8c54-c40804d5cb49.png">

**Comment by raydeal** [comment]
I can't reproduce that in **Misago 0.30**. Moving from HStore to JSONB is good idea. HStoreField is only used for `profile_fields` so it is only one place to change. I think that Postgres will migrate and check type correctly if migration will be done in db, not through Python libs - newer version of Postgres use `hstore_to_jsonb` when value is casted to jsonb.
When I dived deeply I found that `profile_fields` is not null and django put there empty string ('').
```
misago=# SELECT COUNT(*) FROM misago_users_user WHERE profile_fields = '';
 count 
-------
  3141
(1 row)

```
After migration to JSONB, empty string was replaced with dict.
```
misago=# SELECT COUNT(*) FROM misago_users_user WHERE profile_fields = '{}'::jsonb;
 count 
-------
  3141
(1 row)
```
```
misago=# SELECT profile_fields FROM misago_users_user LIMIT 1;
 profile_fields 
----------------
 {}
(1 row)
```
It will be easier to find a reason with JSONField in case of any error.

**Comment by ro1and** [comment]
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">RuntimeError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'profile_fields' has wrong type! Please post this WHOLE message on https://github.com/rafalp/Misago/issues/1352 OID: '((), ())' (valid: '((17280,), (17285,))') Receivers: '&lt;function register_type_handlers at 0x7fe98e1adc60&gt;' (has dead: FALSE) Repr: ''</pre>

Request Method: | GET
-- | --
http://0.0.0.0:8000/
3.2.23
RuntimeError
'profile_fields' has wrong type! Please post this WHOLE message on https://github.com/rafalp/Misago/issues/1352 OID: '((), ())' (valid: '((17280,), (17285,))') Receivers: '<function register_type_handlers at 0x7fe98e1adc60>' (has dead: FALSE) Repr: ''
/srv/misago/misago/users/models/user.py, line 412, in get_real_name
/usr/local/bin/python
3.12.0
['/srv/misago',  '/srv/misago',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/usr/local/lib/python3.12/site-packages']
Sat, 11 Nov 2023 19:00:39 +0000

**Comment by rafalp** [comment]
Thank you for reporting this! With data I've gathered so far, it seems there's a bug in Django where on rare occasions it fails to register HStore extension for database connection.

This bug resolves on itself upon docker restart and seems to only affect dev setups on localhost. Still, its annoying and I plan to move Misago away from HStore to JSON fields in one of future versions.

**Comment by rafalp** [comment]
Related to: #1755
