### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by vladyslav2** [rafalp/Misago#494]
When i tried to run forum with default settings, i got that error:

Traceback (most recent call last):
  File "/home/vladka/forum.webdevelop.pro/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/vladka/forum.webdevelop.pro/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/vladka/forum.webdevelop.pro/env/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./misago/threads/middleware.py", line 5, in <module>
    from misago.threads.counts import (ModeratedCount, NewThreadsCount,
  File "./misago/threads/counts.py", line 9, in <module>
    from misago.threads.views.moderatedcontent import ModeratedContent
  File "./misago/threads/views/moderatedcontent.py", line 7, in <module>
    from misago.threads.views.generic.threads import Threads, ThreadsView
  File "./misago/threads/views/generic/__init__.py", line 4, in <module>
    from misago.threads.views.generic.goto import *
  File "./misago/threads/views/generic/goto.py", line 4, in <module>
    from misago.threads import goto
  File "./misago/threads/goto.py", line 6, in <module>
    from misago.readtracker.threadstracker import make_read_aware
  File "./misago/readtracker/threadstracker.py", line 6, in <module>
    from misago.readtracker import forumstracker, signals
  File "./misago/readtracker/forumstracker.py", line 6, in <module>
    from misago.readtracker import signals
  File "./misago/readtracker/signals.py", line 4, in <module>
    from misago.threads.signals import move_thread, remove_thread_participant
  File "./misago/threads/signals.py", line 114, in <module>
    @receiver(pre_delete, sender=get_user_model())
  File "/home/vladka/forum.webdevelop.pro/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 137, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/home/vladka/forum.webdevelop.pro/env/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/vladka/forum.webdevelop.pro/env/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

in misago default settings:
AUTH_USER_MODEL = 'misago_users.User'

but seems that now work.

Am i doing anything wrong ? Or its a bug ?

**Comment by rafalp** [comment]
Misago 0.5 will not run with Django 1.7. Misago 0.6 will, but that one is still too early. I'm tagging this one as "Docs" so I'll remember to update readme to explain that.

**Comment by rafalp** [comment]
readme updated
