### ISSUE TITLE
Cannot find module './Header' when gulp build

### ISSUE THREAD

**Issue by Macsch15** [rafalp/Misago#569]
```
root@phpdev:/var/www/default/test/Misago/frontend# gulp build
[13:43:46] Using gulpfile /var/www/default/test/Misago/frontend/gulpfile.js
[13:43:46] Starting 'lintsource'...
[13:43:46] Starting 'style'...
[13:43:46] Starting 'copyfonts'...
[13:43:46] Starting 'copyimages'...
[13:43:46] Starting 'vendorsources'...
[13:43:46] Starting 'copyzxcvbn'...
[13:43:46] Finished 'copyzxcvbn' after 342 ms
[13:43:47] gulp-image-optimization: ✔ site-icon.png (saved 2.8 kB)
[13:43:47] Finished 'copyfonts' after 1.14 s
[13:43:49] Finished 'style' after 2.94 s
[13:43:55] Finished 'vendorsources' after 8.54 s
[13:43:55] Finished 'lintsource' after 8.86 s
[13:43:55] Starting 'source'...
[13:43:58] gulp-image-optimization: ✔ site-logo.png (saved 14.1 kB)
[13:43:58] Finished 'copyimages' after 12 s
[13:43:58] Starting 'static'...
[13:43:58] Finished 'static' after 19 μs
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './Header' from '/var/www/default/test/Misago/frontend/src/components/profile'
    at /var/www/default/test/Misago/frontend/node_modules/resolve/lib/async.js:55:21
    at load (/var/www/default/test/Misago/frontend/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/default/test/Misago/frontend/node_modules/resolve/lib/async.js:92:31)
    at /var/www/default/test/Misago/frontend/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by rafalp** [comment]
Fix't, thanks
