### ISSUE TITLE
Can't install new apps

### ISSUE THREAD

**Issue by ioanb7** [rafalp/Misago#620]
Hi Rafal,

I'm trying to add a few django modules to the forum and I am getting some kind of erorr.
Where should I put my `INSTALLED_APPS` ?

Right now under: `mforum3/mforum3/settings.py`, i've added:
"""
INSTALLED_APPS = (

    'django.contrib.staticfiles',
    'debug_toolbar',)
"""

And I am getting:

```
ubuntu@ubuntu-xenial:/vagrant/mforum3$ sudo python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django_debug_toolbar-1.4-py2.7.egg/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/usr/local/lib/python2.7/dist-packages/django_debug_toolbar-1.4-py2.7.egg/debug_toolbar/settings.py", line 227, in patch_all
    patch_middleware_classes()
  File "/usr/local/lib/python2.7/dist-packages/django_debug_toolbar-1.4-py2.7.egg/debug_toolbar/settings.py", line 206, in patch_middleware_classes
    if not is_toolbar_middleware_installed():
  File "/usr/local/lib/python2.7/dist-packages/django_debug_toolbar-1.4-py2.7.egg/debug_toolbar/settings.py", line 188, in is_toolbar_middleware_installed
    for middleware in settings.MIDDLEWARE_CLASSES)
  File "/usr/local/lib/python2.7/dist-packages/django_debug_toolbar-1.4-py2.7.egg/debug_toolbar/settings.py", line 188, in <genexpr>
    for middleware in settings.MIDDLEWARE_CLASSES)
  File "/usr/local/lib/python2.7/dist-packages/django_debug_toolbar-1.4-py2.7.egg/debug_toolbar/settings.py", line 179, in is_middleware_class
    middleware_cls = import_string(middleware_path)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/Misago-0.6a1.dev1-py2.7.egg/misago/users/middleware.py", line 4, in <module>
    from django.contrib.auth.models import AnonymousUser as DjAnonymousUser
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/contrib/auth/models.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/contrib/contenttypes/models.py", line 161, in <module>
    class ContentType(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.10-py2.7.egg/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

Regards,
Ioan.

**Comment by rafalp** [comment]
Please consult Django's documentation and don't use issue tracter for support requests, we have forum for that. :]

**Comment by ioanb7** [comment]
I wish I could've posted it on the forum, unfortunately I didn't receive an e-mail.

In the mean time, I've found the answer under misago/conf/defaults.py
```
Misago default settings

This fille sets everything Misago needs to run.

If you want to add custom app, middleware or path, please update setting vallue
defined in this file instead of copying setting from here to your settings.py.

Yes:

#yourproject/settings.py
INSTALLED_APPS += (
    'myawesomeapp',
)

No:

#yourproject/settings.py
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'misago.core',
    'misago.conf',
    ...
    'myawesomeapp',
)
```

So I made it this way:
```
INSTALLED_APPS += (
'django.contrib.staticfiles',
'debug_toolbar',)
```

**Comment by rafalp** [comment]
Yep, thats the way to go about it.

BTW, there should be debug_toolbar enabled in the core, It's mistake that it's commented out in default config ;)
